# -*- coding: utf-8 -*-
"""从 codec/codec_tables.json 生成 build/codec_tables.h（供 C++ 测试程序用）。
DLL 本体运行时从游戏内存读表；测试用静态表（M0 已验证两者一致）。"""
import json
import sys
from pathlib import Path

root = Path(__file__).resolve().parent.parent
d = json.loads((root / "codec" / "codec_tables.json").read_text(encoding="utf-8"))
out = root / "build"
out.mkdir(exist_ok=True)

def fmt(tables):
    lines = []
    for t in tables:
        b = bytes.fromhex(t)
        assert len(b) == 256
        lines.append("    {" + ",".join(str(x) for x in b) + "}")
    return ",\n".join(lines)

h = f"""// AUTO-GENERATED by gen_tables.py — do not edit
#pragma once
#include "quiz_protocol.h"
static const uint8_t G_ENC[10][256] = {{
{fmt(d['encode'])}
}};
static const uint8_t G_DEC[10][256] = {{
{fmt(d['decode'])}
}};
static inline void load_static_tables(qp::Tables& tb) {{
    memcpy(tb.enc, G_ENC, sizeof tb.enc);
    memcpy(tb.dec, G_DEC, sizeof tb.dec);
    tb.valid = true;
}}
"""
(out / "codec_tables.h").write_text(h, encoding="utf-8")
print("written", out / "codec_tables.h")
